<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="YISC1100384LT" failures="5" tests="9" name="Surefire test" time="12.83" errors="0" timestamp="2024-05-09T11:08:39 IST">
  <testcase classname="api.Test.DDTests" name="testPostUser" time="0.78">
    <failure type="org.testng.internal.reflect.MethodMatcherException" message="
[public void api.Test.DDTests.testPostUser(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: testPostUser([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=4, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=5, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=6, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) ,(java.lang.String) ,(java.lang.String) ]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void api.Test.DDTests.testPostUser(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: testPostUser([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=4, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=5, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=6, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) ,(java.lang.String) ,(java.lang.String) ]
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testPostUser -->
  <testcase classname="api.Test.DDTests" name="deleteUserByName" time="2.642">
    <failure type="java.lang.AssertionError" message="expected [200] but found [405]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [405]
at api.Test.DDTests.deleteUserByName(DDTests.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- deleteUserByName -->
  <testcase classname="api.Test.DDTests" name="deleteUserByName" time="1.188">
    <failure type="java.lang.AssertionError" message="expected [200] but found [405]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [405]
at api.Test.DDTests.deleteUserByName(DDTests.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- deleteUserByName -->
  <testcase classname="api.Test.DDTests" name="deleteUserByName" time="1.153">
    <failure type="java.lang.AssertionError" message="expected [200] but found [405]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [405]
at api.Test.DDTests.deleteUserByName(DDTests.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- deleteUserByName -->
  <testcase classname="api.Test.HerokuappUserTest" name="dataDrivenTesting" time="0.0">
    <failure type="org.testng.TestNGException" message="
Method public void api.Test.HerokuappUserTest.dataDrivenTesting(java.util.Map) throws java.io.IOException requires a @DataProvider named : ExcelTestData">
      <![CDATA[org.testng.TestNGException: 
Method public void api.Test.HerokuappUserTest.dataDrivenTesting(java.util.Map) throws java.io.IOException requires a @DataProvider named : ExcelTestData
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- dataDrivenTesting -->
  <testcase classname="api.Test.UserTests" name="testPostUser" time="1.569"/>
  <testcase classname="api.Test.UserTests" name="testGetUserByName" time="1.187"/>
  <testcase classname="api.Test.UserTests" name="testUpdateUserByName" time="2.296"/>
  <testcase classname="api.Test.UserTests" name="deleteUserByName" time="1.169"/>
</testsuite> <!-- Surefire test -->
